# Generated by Django 5.0.2 on 2024-02-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_remove_post_updated_at_alter_post_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="UPDATE DT"),
        ),
    ]
