CREATE TABLE EMPLOYEE (
	EMPLOYEE_NO VARCHAR2(5 BYTE),
	NAME VARCHAR2(30 BYTE),
	POSITION NUMBER(1),
	SALARY NUMBER(10)
)


CREATE TABLE EMPLOYEE_DISPATCH (
	EMPLOYEE_NO VARCHAR2(5BYTE),
	DISPATCH_FLAG NUMBER(1),
	DISPATCH_START_DATE DATE
)

CREATE TABLE POSITION_LIST (
	POSITION_NO NUMBER(1),
	POSITION_NAME VARCHAR2(24)
)

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_NO);

ALTER TABLE POSITION_LIST ADD CONSTRAINT POSITION_LIST_PK PRIMARY KEY (POSITION_NO);

ALTER TABLE EMPLOYEES ADD CONSTRAINT EMPLOYEE_POSITION_LIST_FK FOREIGN KEY (POSITION)
REFERENCES POSITION_LIST (POSITION) ON DELETE CASCADE;

ALTER TABLE EMPLOYEE_DISPATCH ADD CONSTRAINT EMPLOYEE_DISPATCH_EMPLOYEE_FK 
FOREIGN KEY (EMPLOYEE_NO) REFERENCES EMPLOYEE (EMPLOYEE_NO) ON DELETE CASCADE;

INSERT INTO EMPLOYEE VALUES('1001', '이세연', 1, 100000);
INSERT INTO EMPLOYEE VALUES('1002', '윤수빈', 2, 200000);
INSERT INTO EMPLOYEE VALUES('1003', '이수현', 3, 300000);
INSERT INTO EMPLOYEE VALUES('1004', '김한봄', 4, 400000);
INSERT INTO EMPLOYEE VALUES('1005', '양지수', 5, 500000);


INSERT INTO EMPLOYEE_DISPATCH VALUES('1001', 1, '2001-01-01');
INSERT INTO EMPLOYEE_DISPATCH VALUES('1002', 1, '2001-01-02');
INSERT INTO EMPLOYEE_DISPATCH VALUES('1003', 0, '2001-01-03');
INSERT INTO EMPLOYEE_DISPATCH VALUES('1004', 0, '2001-01-04');
INSERT INTO EMPLOYEE_DISPATCH VALUES('1005', 1, '2001-01-05');


INSERT INTO POSITIO_LIST VALUES(1, '사원');
INSERT INTO POSITIO_LIST VALUES(2, '대리');
INSERT INTO POSITIO_LIST VALUES(3, '부장');
INSERT INTO POSITIO_LIST VALUES(4, '차장');
INSERT INTO POSITIO_LIST VALUES(5, '사장');

ROLLBACK INSERT_DATA_FIN;

CREATE INDEX EMPLOYEE_DISPATCH_INDEX ON EMPLOYEE_DISPATCH(DISPATCH_FLAG);

SELECT DISPATCH_FLAG FROM EMPLOYEE_DISPATCH, POSITION_LIST, EMPLOYEE WHERE DISPATCH_FLAG IS 0;

SELECT E.EMPLOYEE_NO, N.NAME, P.POSITION_NAME, S.SALARY 
FROM EMPLOYEE E, EMPLOYEE_DISPATCH D, POSITION_LIST P
WHERE E.EMPLOYEE = D.EMPLOYEE AND L.POSITION NAME = E.POSITION NAME

CREATE OR REPLACE VIEW RESULT_LIST
AS SELECT E.EMPLOYEE_NO, N.NAME, P.POSITION_NAME, S.SALARY 
FROM EMPLOYEE E, EMPLOYEE_DISPATCH D, POSITION_LIST P
WHERE E.EMPLOYEE = D.EMPLOYEE AND L.POSITION NAME = E.POSITION NAME